### ISSUE TITLE
rendering via an S3 URL

### ISSUE THREAD

**Issue by freeeal** [badunk/multer-s3#1]
i'm trying render an image via an S3 url in the following form:

"'https://s3.amazonaws.com/bucket-name/'+ req.file.key" 

where req.file.key is my storage's dirname attribute; however, i keep getting the following error when i navigate to said URL: "This XML file does not appear to have any style information associated with it. The document tree is shown below." i'm not sure if this is an issue with multer itself or this module for storing to my s3 bucket. i do indeed have my storage acl set to 'public-read'.

if this helps, logging 'req.file' to the console returns an object with all the proper metadata, where the size is "undefined." if you could let me know what you think Duncan, that'd be great!

**Comment by LinusU** [comment]
This could probably still have something to do with `acl` since that can be set per request. Could you try to run `curl https://s3.ama...` and then paste the xml output, that should give you a more specific error.

**Comment by freeeal** [comment]
i'm pretty sure the error is not related to the acl, but rather that amazon s3 isn't recognizing the content type of the image even though multer itself is recognizing as mimetype 'image/jpeg' -- i.e. all my s3 files are of content type 'application/octet-stream.' i'm not sure where exactly the fix needs to be made however.. maybe specify content type within multer's storage option?

however, i'm not entirely sure how logically to fix this error.

**Comment by freeeal** [comment]
yeah you're right -- it was an acl problem. i could've sworn that i had set public privileges but apparent not 0.o... thanks for being helpful, Linus.

**Comment by LinusU** [comment]
Hehe, no problem :)
