### ISSUE TITLE
multer-s3 AWS s3 response handling.

### ISSUE THREAD

**Issue by javavenkats5** [badunk/multer-s3#100]
I am using multer-s3 code below to upload the image to aws s3 bucket , it is successfully uploaded. But i want to print the etag of the uploaded image which s3 returns. Please help how to hold the response from this multer-s3 also how to handle the error?

var upload = multer({
    storage: multerS3({
        s3: s3,
        bucket: BUCKET_NAME,
        key: function (req, file, cb) {
        cb(null, Date.now()+'-'+file.originalname);
        }
    })
});
app.post('/postimage', uploader.array('image',1),function (req, res) {
  res.send('uploaded');
})

**Comment by LinusU** [comment]
The etag will be part of the file object:

```js
for (const file in req.files) {
  console.log(file.etag)
}
```
