### ISSUE TITLE
random files uploaded to my S3 bucket

### ISSUE THREAD

**Issue by bitfede** [badunk/multer-s3#110]
Hello!

I succesfully got images saved to my S3 bucket! multer-s3 is an amazing add-on!

I just have one little problem, I find myself with many many random files saved to the same S3 bucket... without me having any interaction with the software, here is a screenshot:

<img width="1163" alt="screen shot 2018-09-27 at 5 27 34 pm" src="https://user-images.githubusercontent.com/15684622/46157134-5e14fd80-c27b-11e8-9c6c-0376e3c0951e.png">

The first file on top is the one I received from a POST request, and it's perfect! But below, I have a series of files that get created every minute or so, and I have no idea how to stop this and why it's happening...

Any kind dev can help me figure this out? thank you so much!!

**Comment by LinusU** [comment]
Is your server accessible from the internet? Do you have any authentication before the file upload code?

**Comment by bitfede** [comment]
ah, turned out to be Amazon S3's logging that was creating the files... :)

found the fix in this stackoverflow thread:
[https://stackoverflow.com/questions/45409432/lots-of-files-appearing-in-my-amazon-s3-bucket](url)
