### ISSUE TITLE
How to get back the public Bucket file URL after upload? (Single file)

### ISSUE THREAD

**Issue by somikdatta** [badunk/multer-s3#129]
I can't figure out how to extract the public URL of the uploaded file for sending back to user.

**Comment by sauldeleon** [comment]
Hi @somikdatta 
How do you retrieve the url?
thanks!

**Comment by somikdatta** [comment]
> Hi @somikdatta
> How do you retrieve the url?
> thanks!

Hey @sauldeleon!
Multer appends the file location in req.file.location which you can access on the next middleware.
