### ISSUE TITLE
Is the package still usable ?

### ISSUE THREAD

**Issue by tucosaurus** [badunk/multer-s3#135]
Considering the last commit was in July, 2018 by @LinusU. Should people still be using this package ?

**Comment by LinusU** [comment]
It's still usable, and works great with Multer 1.x

With that being said, Multer 2.x is around the corner and is changing to an approach which makes storage engines obsolete

**Comment by tucosaurus** [comment]
Thank you for replying. :)
Looking forward to Multer 2.x
