### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by TonhaoSantos** [badunk/multer-s3#147]
When I run ```yarn upgrade``` on my project a dependency of you updated.

This dependency has a package that is broken.

Your dependence:
![image](https://user-images.githubusercontent.com/12022023/108159482-ed7a1000-70c5-11eb-9753-f3426bd62da8.png)

broken package:

![image](https://user-images.githubusercontent.com/12022023/108159672-3df16d80-70c6-11eb-9675-9d76b4542978.png)

Reverted, but it's good to warn you about: D

**Comment by andyryan** [comment]
Just hitting this issue ourselves. Do you know what the last stable version of multer-s3 is.

In our case this is manifesting in the key callback returning undefined, meaning no file gets uploaded.

**Comment by TonhaoSantos** [comment]
It is no longer giving this error in the current version. Dependency fix the problem.
