### ISSUE TITLE
`dirname` is not documented

### ISSUE THREAD

**Issue by Sparragus** [badunk/multer-s3#15]
If I `npm install multer-s3`, it downloads `v1.4.1`. However, the documentation is for versions of multer ahead of `v1.4.1` where `dirname` is not longer a required option.

I suggest that while `multer-s3@1.4.1` is the default on `npm` we bring back all the documentation needed for using the module.

It took me a while to figure out what was going on.

**Comment by badunk** [comment]
I think part of the problem is that I'm not tagging before I publish.  I'll start doing that so its more clear from now on.  Otherwise, I do believe that the current version of the README should always reflect the current status of the code.

**Comment by Sparragus** [comment]
Tagging sounds good. Thanks.

Richard Kaufman

**Comment by badunk** [comment]
https://github.com/badunk/multer-s3/tree/1.4.1

Thanks for the heads up!

**Comment by LinusU** [comment]
protip, use `npm version _ -m 'version: %s'` to update `package.json`, create a new commit and tag the commit. Replace `_` with `major`, `minor` or `patch`.

**Comment by LinusU** [comment]
Also, I would like to get the next major version published, working on a rather big pull request now which could be it. It's going to need some review and discussion though :+1:

**Comment by Sparragus** [comment]
If be happy to help reviewing.

On Tuesday, January 26, 2016, Linus Unnebäck <notifications@github.com>
wrote:

> Also, I would like to get the next major version published, working on a
> rather big pull request now which could be it. It's going to need some
> review and discussion though [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/badunk/multer-s3/issues/15#issuecomment-175227997>.
>


-- 
Richard Kaufman

**Comment by badunk** [comment]
@LinusU ah, great thanks!  I was looking for that exact command
