### ISSUE TITLE
Unmet dependencys - multer-s3 ^3.0.0

### ISSUE THREAD

**Issue by JotaOdiceu** [badunk/multer-s3#175]
When I run "yarn install multer-s3", the following warnins are shown:
```bash
warning "> multer-s3@3.0.1" has unmet peer dependency "@aws-sdk/client-s3@^3.0.0".
warning "multer-s3 > @aws-sdk/lib-storage@3.100.0" has unmet peer dependency "@aws-sdk/abort-controller@^3.0.0".
warning "multer-s3 > @aws-sdk/lib-storage@3.100.0" has unmet peer dependency "@aws-sdk/client-s3@^3.0.0".
```

This has been happening since version 3.0.0, in previous versions this did not happen, to correct I am performing a workaround installing the unmet dependencies individually.

**Comment by Takaitra** [comment]
I took a look and these are both valid peer dependencies.

1. Both `lib-storage` and `multer-s3` are compatible with `@aws-sdk/client-s3@^3.0.0`. The consumer should declare an explicit dependency on the version of `client-s3` they prefer.
2. `@aws-sdk/abort-controller` is an optional peer [dependency of lib-storage](https://github.com/aws/aws-sdk-js-v3/blob/efdc6a062180b7ca5fc4ad149c50800f86bb1268/lib/lib-storage/package.json). The consumer should explicity declare a dependency on `abort-controller` if they need it.

These peer dependencies are working as intended so installing them individually is the proper fix for the warning, not a workaround.

**Comment by JotaOdiceu** [comment]
I understand, in versions prior to 3.0.0 of `multer-s3`, these dependencies were not "necessary" and `multer-s3` worked well alongside the `aws-sdk` package. As I understand it, now in this update it is necessary to install these additional dependencies, that is?

**Comment by LinusU** [comment]
@JotaOdiceu as you can see [here in the readme](https://github.com/anacronw/multer-s3#aws-sdk-versions), version 3.x of `multer-s3` works with the new `@aws-sdk/client-s3` package, whilst version 2.x of `multer-s3` works with the old `aws-sdk` package. When you upgrade to 3.x you must also upgrade to the new AWS SDK at the same time...
