### ISSUE TITLE
Larger files fail silently

### ISSUE THREAD

**Issue by aug2uag** [badunk/multer-s3#179]
I've encountered an issue where larger file sizes (⪆ 25MB) silently fail. This issue was reported several times elsewhere by others for example [here](https://stackoverflow.com/questions/47885229/i-am-not-able-to-upload-large-files-using-multer-s3-it-is-not-giving-me-any-err), [issue #69], [another](https://html.developreference.com/article/14694458/nodejs+AWS+and+multer-s3+failing+silently), and there are more.

The [params](https://github.com/anacronw/multer-s3/blob/2c3e5328957eeb6ea6810284b8711e416b708c0e/index.js#L192) are missing [AWS ContentLength property](https://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/P_Amazon_Runtime_AmazonWebServiceResponse_ContentLength.htm). I tested this and verified adding ContentLength resolved my issue.

**Comment by aug2uag** [comment]
Update: this seemed to have solved my issue on localhost yet it turned out my issues in staging were related to web proxy configs that have been sorted out. Feel free to close this issue. I'll get around to testing my staging instance without the ContentLength in params and will report back if there are any findings.

**Comment by elirichey** [comment]
@aug2uag Can you please elaborate which configs you updated? I'm running into the same issue.

**Comment by aug2uag** [comment]
@elirichey it depends on your webproxy (whether you use one), for me on NGINX it was related to `proxy_pass` and experimenting with settings related there
