### ISSUE TITLE
npm is not installing correct version.

### ISSUE THREAD

**Issue by higgspa** [badunk/multer-s3#18]
Duncan,
FYI - I noticed that npm is not installing the latest version of your package. The version numbers match but the index.js from npm does not match the index.js from this git repo. Using the version from this repo works great. 

Steve

**Comment by LinusU** [comment]
We are waiting for #16 and then we'll release 2.0. It's my fault that this is taking some time, I'll try to go through and fix it soon :+1:

**Comment by badunk** [comment]
Please checkout version `1.5.0`
