### ISSUE TITLE
File Extension

### ISSUE THREAD

**Issue by jjordy** [badunk/multer-s3#19]
Hi I am using your library with some success. But I was curious what your recommended way to add a file extension is? I tried the key attribute that is passed into the options but It seems the docs are outdated. Let me know how you normally handle this.

Thanks,

Jordy

**Comment by badunk** [comment]
I'm assuming you're using v.1.4.1 on npm:

https://github.com/badunk/multer-s3/tree/1.4.1

The documentation on there should match, namely the `filename` function.

**Comment by jjordy** [comment]
Yeh! I figured it out man! Was just about to close the issue I see you already provided everything I needed was just looking at the wrong docs.

**Comment by badunk** [comment]
great :D

**Comment by jjordy** [comment]
No worries honestly i should have just looked at your code before i opened the issue. It was write in front of my eyes :100:
