### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by cjurjiu** [badunk/multer-s3#211]
Last publish was 2 years ago, several nice PR's left unanswered (examples would be [this](https://github.com/anacronw/multer-s3/pull/206) & [this](https://github.com/anacronw/multer-s3/pull/194), but there are more)

Not trying to be disrespectful, just curious of the state of the project.

Best 👋

**Comment by Striar-Yunis** [comment]
I have forked the repository [here](https://github.com/Striar-Yunis/multer-s3).

I believe I've preserved all of the existing interfaces while doing the following:
1. Re-written in typescript with commonjs and esm support
2. Updated all of the outdated dependencies
3. Added await support, can now pass async functions that return the desired value.
4. Added tagging support based on [this](https://github.com/anacronw/multer-s3/pull/206).
5. Added partsize support (to allow uploads over 48.8GB to AWS)

It has been published to: https://www.npmjs.com/package/multer-s3-extended?activeTab=readme

If you hit something that isn't compatible lmk. I'll update the readme over the next several days.

**Comment by cjurjiu** [comment]
Amazing work @Striar-Yunis! 

Thanks for your effort, I cannot overstate how big of a positive surprise this is. I was also thinking to do the same, just didn't find the time to get to it until now. 

Will migrate as soon as I can. Cheers!
