### ISSUE TITLE
Delete files

### ISSUE THREAD

**Issue by aamirafridi** [badunk/multer-s3#23]
Is there a support to delete files?
If yes can you please give example

**Comment by badunk** [comment]
sorry I don't think file deletion will be supported, will be out of scope.

We are using the underlying aws-sdk, which has that support that you need.

**Comment by stillatmylinux** [comment]
`router.post('/s3/delete', (req, res) => {

	console.log(req.body.images);

	var deleteItems = [];

	req.body.images.forEach(function(item){
		deleteItems.push({Key:item.key});
	});
	  
	var params = {
		Bucket: 'mybucket-dev', 
		Delete: {
			Objects: deleteItems, 
			Quiet: false
		}
	};

	s3.deleteObjects(params, function(err, data) {
		if (err) console.log(err)     
		else console.log("Successfully deleted myBucket/myKey");   
	});

	res.json({
		message: 'images deleted',
		items: deleteItems
	});
});`
