### ISSUE TITLE
Overwriting 

### ISSUE THREAD

**Issue by arturojain** [badunk/multer-s3#25]
There should be a way to disable file overwriting. Maybe something like:

```
var upload = multer({
  storage: s3({
    bucket: 'some-bucket',
    secretAccessKey: 'some secret',
    accessKeyId: 'some key',
    region: 'us-east-1',
    overwrite: false,
    key: function (req, file, cb) {
      cb(null, Date.now().toString())
    }
  })
})

```

**Comment by badunk** [comment]
The crypto is there just to provide a unique signature for the file so no overwriting should be occurring unless you define your own function.

I'm not sure of your use case of course, but I would be wary of allowing your users to control that aspect of it by crafting their own filenames etc if its not sufficiently random.

**Comment by arturojain** [comment]
I mean, we could me it easier to overcome this common [issue](http://stackoverflow.com/questions/10592541/amazon-s3-acl-for-read-only-and-write-once-access).

**Comment by badunk** [comment]
You can of course define your own key for it to be sufficiently random.  You'll have to turn on versioning on the bucket yourself if you want that feature.
