### ISSUE TITLE
Link after upload

### ISSUE THREAD

**Issue by thebergamo** [badunk/multer-s3#28]
Have a way to referencing the link on the `req` object after the complete upload to s3?

**Comment by badunk** [comment]
You should be able to attach another middleware to do that.  In fact, that is how you can access the files that were uploaded if you check out the README

**Comment by LinusU** [comment]
@thebergamo You can also see it as `location` on the file object, e.g. `req.file.location`.

**Comment by LinusU** [comment]
@badunk Maybe we should add all the exposed props on the file object to the readme?

**Comment by badunk** [comment]
oh that's a good idea

**Comment by thebergamo** [comment]
haha sorry, after reading the source code I assume it, I can see a lot of information in `req.file` in the next middleware.

Thanks for that! Will be very appreciate if this infos are exposed in README :)

**Comment by superirale** [comment]
i'm quite confused on how to get the location using req.file

**Comment by badunk** [comment]
@superirale you're not trying to get the location - you tell the middleware where to store in s3.  The s3 key/bucket is determined by you.

**Comment by superirale** [comment]
No worries guys. issue solved.
