### ISSUE TITLE
Drop the dependency on s3fs

### ISSUE THREAD

**Issue by LinusU** [badunk/multer-s3#3]
I think it would be a good improvement to drop the dependency on `s3fs` and instead use `aws-sdk` directly. This would save the extra dependencies and give us access to upstream updates quicker.

I would be happy to provide the code if no one beats me to it.

On a related note, it seems like uploading to s3 from multer is very popular. How would you feel about getting some help on maintaining this module? I would personally be happy to hop on as a maintainer. Since it's such a small module I think the most work would be to cut new releases when dependencies (probably only `aws-sdk`) updates, and to answer questions from users.

I'm `linusu` on npm :smile:

**Comment by badunk** [comment]
I'd love help on this module!  The only real value I added was making sure the integration worked - the rest was trivial yet I didn't see other modules doing the same thing.  I don't have much time myself on open source unfortunately.

I'd be happy to take any pull requests.  I can also add you as a maintainer
