### ISSUE TITLE
Target folder

### ISSUE THREAD

**Issue by ace-eddy** [badunk/multer-s3#33]
```
var upload = multer({
  storage: multerS3({
    s3: s3,
    bucket: 'web-test-2016',
    acl: 'public-read',
    key: function (req, file, cb) {
      cb(null, makeid() + '_' + file.originalname)
      //Date.now().toString()
    }
  })
})
```

In this case, how can I set the destination folder name? Thanks.

**Comment by LinusU** [comment]
S3 doesn't have real folders, to get what you want you can just append folder name followed by a `/` to the key.

**Comment by caseyhyde** [comment]
Just tried this, and works great! However by append, he means prepend. Ie: `foo/ + makeid() + '_' + file.originalname` puts file in folder names `foo` with a url of `https://s3.amazonaws.com/bucketname/foo-folder/id_file.originalname`
