### ISSUE TITLE
Specify key on endpoint

### ISSUE THREAD

**Issue by anaibol** [badunk/multer-s3#40]
Hi! Thanks for this useful middleware.
I was looking for the possibility to specify a prefix in the endpoint like:
``` javascript
app.post('/', upload.array('images', 5, 'user_images_prefix'), req, res) => {}
```

**Comment by LinusU** [comment]
Hi, glad to hear that you like it :)

What would the prefix be used for?

**Comment by anaibol** [comment]
The idea is to set a custom path for each upload endpoint. The endpoint for user images would point the uploads to bucket/users/filename.jpg.

**Comment by anaibol** [comment]
I resolved that adding a prefix parameter to my upload middleware:
``` javascript
app.post('/', upload('user').array('images', 5)), req, res) => {}
```

**Comment by LinusU** [comment]
Nice 👌
