### ISSUE TITLE
File param not recognized.

### ISSUE THREAD

**Issue by aconfee** [badunk/multer-s3#42]
Hello,

I've implemented setup for multer-s3 exactly as you have demonstrated. It looks like file uploading to s3 is working! However, the file object passed to the metadata and key functions does not have a key or location, even though it is successfully uploading.

Ultimately, my goal is to upload the file, but also return the filepath as a json response back down to my client. How would you recommend doing this? Why does the file object seem to be empty, and what are the metadata and key functions even meant to do?

Thanks,
Adam

**Comment by LinusU** [comment]
Can you please share the code that you are using?

**Comment by aconfee** [comment]
Sure thing! I've created a gist to make it easier to read:
https://gist.github.com/aconfee/5348d4f68fd60dda2b34d368c5e0ab1c

The console output is provided in the gist. Again, the correct files are uploading to S3, I'm just trying to understand how I can capture some of the file's information to send back to my client. Thanks for looking at this!

P.S. I realize the path I'm currently sending back is incorrect as well, I'm trying to get the S3 file location as well which I assume is file.location, but as mentioned, can't access this.

**Comment by LinusU** [comment]
`location` will only be available once the file is uploaded, use it in your route handler as such: `req.files[0].location`

(Am on mobile, hence the short answer)

**Comment by aconfee** [comment]
Ah, there it is. I was using file members from multer, not multer-s3. I'm getting all the info I need in my route handler now, thanks! 

By adding the returned location to the 'src' attribute of one of my images, I'm getting a 403 'forbidden' error. I've already updated my CORS config in S3, and I may be missing some other details that I need to work out with S3, but I'm wondering, is there anything in multer-s3 that might/should make this process easier? Or does this sound like an s3 problem? Thanks!

**Comment by LinusU** [comment]
@aconfee The multer-s3 module has a option to set ACL (amazons access settings). Setting it to `public-read` (or something similar, can't quite remember) should make it publicly readable

**Comment by aconfee** [comment]
Thanks!

**Comment by LinusU** [comment]
Link to docs: https://github.com/badunk/multer-s3#setting-acl
