### ISSUE TITLE
S3 Object Upload Cancellation

### ISSUE THREAD

**Issue by tsambora** [badunk/multer-s3#45]
Is there any way to cancel the file upload? Say if the request is unauthorized and we don't want the file from the request to be uploaded to S3.

**Comment by LinusU** [comment]
You could put a middleware that checks for authentication before the multer middleware. That way you can abort before uploading even begins...

**Comment by tsambora** [comment]
Ah yes. Thanks for your quick response. This is helpful.

**Comment by LinusU** [comment]
No problem :ok_hand:
