### ISSUE TITLE
Image preprocessing before upload to s3

### ISSUE THREAD

**Issue by kenoung** [badunk/multer-s3#47]
Hi, I was wondering whether it was possible to perform some image preprocessing with lwip (https://github.com/EyalAr/lwip#usage) prior to upload?

**Comment by panasevich** [comment]
Hi @kenoung!
What solution did you find?

**Comment by kenoung** [comment]
@panasevich I didnt. I needed this because the (cropper)[https://github.com/fengyuanchen/cropper/blob/master/README.md] I was using provided me with coordinates. So I switched to a different (library)[https://github.com/Foliotek/Croppie] that did the cropping on the front end.

Sorry I can't help!
