### ISSUE TITLE
Get response from S3

### ISSUE THREAD

**Issue by sprakashg** [badunk/multer-s3#5]
I used it this way.

```javascript
var multer = require('multer');
var s3 = require('multer-s3');

var upload = multer({
storage: s3({
dirname: 'uploads/photos',
bucket: 'testing-bucket-yousa',
secretAccessKey: 'abcd',
accessKeyId: 'zz',
region: 'us-east-1'
})
})

app.post('/admin/uploadImagetoS3', upload.array('file'), function (req, res, next) {
console.log(res)
})
```

what does `upload.array('file')` do?

Please clarify me why is dirname required, I don’t want to store the data on my local machine and how to capture the response from s3, if it was successful or not?

**Comment by PLEEROCK** [comment]
+1 for getting response

**Comment by LinusU** [comment]
`dirname` is the name of the "directory" on S3, not on your local machine.

`upload.array('file')` means that it will accept multiple files named "file".

**Comment by LinusU** [comment]
Please reopen if you need more assistance.
