### ISSUE TITLE
create new directory 

### ISSUE THREAD

**Issue by laics1984** [badunk/multer-s3#54]
Hi is it possible to create a new directory in the bucket before uploading? via `dirname`?

Thanks.

**Comment by LinusU** [comment]
S3 doesn't have a concept of folders, you can upload with any directory components in your `key`

**Comment by laics1984** [comment]
hi @LinusU , if the folder doesnt exist, will it be created automatically?

**Comment by LinusU** [comment]
Yes

**Comment by laics1984** [comment]
thanks
