### ISSUE TITLE
var s3 = new aws.S3({ /* ... */ })

### ISSUE THREAD

**Issue by abmnukmr** [badunk/multer-s3#63]
where i put my my s3 access key and 

where i put my my s3 access key and 

**"accessKeyId": "xxxxxxxxxxxxxxxx",
    "secretAccessKey": **"xxxxxxxxxxxxxx",

**i get this error
AWS Missing credentials when i try send something to my S3 Bucket**

**Comment by rvahudson** [comment]
Can you post your code?

**Comment by badunk** [comment]
make sure that user is given access to that bucket on the aws side - its possible its not code related
