### ISSUE TITLE
npm published version 2.7.0 does not match repo 2.5.0

### ISSUE THREAD

**Issue by daneroo** [badunk/multer-s3#70]
The version of this package published on npm is at version 2.7.0
  https://www.npmjs.com/package/multer-s3
The repo has no 2.7.0 tag, and it's head package.json is still at 2.5.0

Perhaps the repo is just missing the 2.7.0 tag, and package.json needs to be bumped

**Comment by badunk** [comment]
sorry! fixed

**Comment by daneroo** [comment]
No problem at all.
I appreciate all you have done.

Also, just FYI, there is some confusion with another npm package [multer-s3-transform](https://www.npmjs.com/package/multer-s3-transform), which was forked from your repo.
Its an interesting derivitive which allows piping to multiple transform streams to s3
