### ISSUE TITLE
How to get req.body parameters in multer s3

### ISSUE THREAD

**Issue by bhavinsa** [badunk/multer-s3#76]
storage: multerS3({
    s3: s3,
    bucket: 'bucket',
    metadata: function(req, file, cb) {
        cb(null, {
            fieldName: file.fieldname
        });
    },
    key: function(req, file, cb) {
        console.log('req.body', req.params.id); //not getting
        console.log('req.body', req.body);
        //Not getting param here that passed in api 
        //Need to save file on s3 at specific location i.e /foldername/filename
        //But the folder name not getting from API
        cb(null, file.originalname)
    }
})  }).array('userFile', 1);

------------------------------------------------------------------------------------------------
Above is multer s3 code

--------------------------------------------------------------------------------------------
app.post('/saveData', function(req, res, next) {
upload(req, res, function(err) {
    console.log('err' + err);
    var status = '';
    var result = '';
    var link = '';
    if (err) {
        status = false;
    } else {
        status = true;
    }
    result = {
        "status": status,
        "link": link
    }
});
res.send(result);   });

--------------------------------------------------------------------------------------------------------

Above code where calling multer upload function. I am parsing data in API (from Angular2, set -Content-Type": "multipart/form-data) as formdata

`let formData: FormData = new FormData();

formData.append('userFile', file);

formData.append('fileName', fileName);`

I require the req.body data from API like folder name and other, so I can put the file to specific place on S3. Need req.body data inside the key: function(req, file, cb) { of multerS3.

**Comment by badunk** [comment]
Neither multer or this repo parses form body.  That is typically done
through express form body parser.

**Comment by bhavinsa** [comment]
@badunk  - 

I have added below code, still, I am not getting inside the multer s3 upload function. 

app.use(bodyParser.urlencoded({
            extended: false
}));

However, I can get it inside 

app.post('/saveData', function(req, res, next) {
    console.log(req.body);   //get data here
});

**Comment by castielblak** [comment]
This is a general multer problem, more info can be found here: https://github.com/expressjs/multer/issues/322

Briefly: reordering your body parameters should help.

**Comment by LinusU** [comment]
Thanks @castielblak!
