### ISSUE TITLE
Error handling with multer-s3

### ISSUE THREAD

**Issue by taniarascia** [badunk/multer-s3#86]
According to the [error handling](https://github.com/expressjs/multer#error-handling) page on multer, this is the code for handling errors:

```js
var upload = multer().single('avatar')

app.post('/profile', function (req, res) {
  upload(req, res, function (err) {
    if (err) {
      // An error occurred when uploading
      return
    }

    // Everything went fine
  })
})
```

However, using multer-s3, the syntax is as follows:

```js
app.post('/upload', upload.array('upload', 1), function (req, res, next) {
  response.send('success');
});
```

The syntax does not match the multer error handling, and my attempts at trying to rewrite the code to allow for the upload function have not been successful. How can I use custom error handling with multer s3?

**Comment by taniarascia** [comment]
Figured it out - just need to move `.array('upload', 1)` to the end of the `multer` function.

```js
var upload = multer().array('upload', 1);

app.post('/upload', function (req, res, next) {
  response.send('success');
});
```

**Comment by anthonywebb** [comment]
@taniarascia can you clarify on your example a bit?  From your last example it looks like the "upload" middleware was never even called?  I have an upload failing silently and am wondering how/where to catch the error

**Comment by anthonywebb** [comment]
I did figure it out, for those who follow this is what my middleware (addImageSimple) looked like:

```
exports.addImageSimple = function(req, res, next) {
    var upload = multer({
        storage: multerS3({
            s3,
            bucket: 'mybucket',
            contentType: multerS3.AUTO_CONTENT_TYPE,
            acl: 'public-read',
            key(req, file, cb) {
                cb(null, Date.now().toString() + '.png'); 
            }
        })
    }).array('images',1);

    upload(req,res, function(err){
        if(err){
            console.log('oops something bad happened while uploading your image')
            console.log(err);  
            res.status(400).json({error: 'unable to create image'});

        } else {
            next();
        }
    })
};
```

**Comment by sarahbethfederman** [comment]
When I do this my json error message doesn't go through and when I call next(err) my error handler isn't called :( has anyone run into this?
