### ISSUE TITLE
Publish 2.8.0

### ISSUE THREAD

**Issue by LinusU** [badunk/multer-s3#92]
I thought I had access to `npm` and tagged a release :)

@badunk would you mind publishing 2.8.0?

```sh
git checkout v2.8.0
npm publish
```

**Comment by LinusU** [comment]
ping @badunk, would you mind adding me as a maintainer on npm? ☺️

**Comment by badunk** [comment]
absolutely!

**Comment by LinusU** [comment]
Thanks, I have published 2.8.0 and 2.9.0 now 🚀
