### ISSUE TITLE
cant retrieve the data object coming back from S3

### ISSUE THREAD

**Issue by rosea1** [badunk/multer-s3#96]
const upload = multer({
  storage: multerS3({
    s3: s3,
    bucket: 'BUKCET',
    key: function (req, file, cb) {
      const extension = file.originalname.split('.').pop();
      const date = new Date().toJSON().slice(0,10);
      fileName = `${crypto.randomBytes(10).toString('hex')}-${date}.${extension}`;
      const data = cb(null, fileName);
      console.log(data);
    }
  })
});

File is uploading to amazon perfectly, however when i did this directly from the front end using the aws-sdk, the bucket.upload function returned a data object with the uploaded files information, such as the path to access the image. 

How do i access this through multer ?

**Comment by LinusU** [comment]
You should be able to see that information at `req.file`, see this part of the readme: https://github.com/badunk/multer-s3#file-information

**Comment by rosea1** [comment]
excellent! got it! stunning bit of software !
