### ISSUE TITLE
After upload, image not readable

### ISSUE THREAD

**Issue by vincelwt** [badunk/multer-s3#97]
Hi! 
I've been trying to upload some image to S3, and show it to the user after. 

The upload is successful, but the images are not readable. 
When I open one of them, it download it but no program can open it (says the image is broken). And if I put the s3 link in a img's src, it also won't work.

I also tried setting the contentType manually or via `multerS3.AUTO_CONTENT_TYPE` without luck.

Here is my code:

```
<form enctype="multipart/form-data"  method='POST' action='/icon'>
    <input onchange="this.parentElement.submit()" type="file" name='icon'>
</form>
```

```
let s3 = new AWS.S3()

let upload = multer({
	storage: multerS3({
		s3: s3,
		acl: 'public-read',
		bucket: 'form-icons',
		contentType: multerS3.AUTO_CONTENT_TYPE,
		key: (req, file, next) => {
			next(null, Date.now().toString() + file.originalname)
		}
	})
})

app.post('/icon', upload.single('icon'), (req, res, next) => {
	res.send('url: ' +req.file.location)
})
```

Anyone might see where I went wrong? 

Thanks.

**Comment by vincelwt** [comment]
Closing since this doesn't seem to be a bug with multerS3 but with multer.

**Comment by goodman98** [comment]
@vincelwt 
I upload images using [react-dropzone](https://github.com/react-dropzone/react-dropzone)
After uploaded, req.file object is like below, and the uploaded image doesn't display but it is downloaded.
```
{
  fieldname: 'file',`
  originalname: 'test.jpg',
  encoding: '7bit',
  mimetype: 'image/jpeg',
  size: 26924,
  bucket: MY-S3-BUCKET,
  key: 'test.jpg',
  acl: 'public-read',
  contentType: 'application/octet-stream',
  contentDisposition: null,
  storageClass: 'STANDARD',
  serverSideEncryption: null,
  metadata: null,
  location: MY-S3-LOCATION,
  etag: '""'
}
```

When I changed 'contentType' to 'image/jpeg', the uploaded image was opened in browser, but displayed wrong.

Can I ask you how to solve this?

**Comment by vincelwt** [comment]
Hi!
My issue is I was using the *serverless* framework with API gateway. 
There was some problems with the binary support which were fixed with a plugin and some configs, see this issue for more details: https://github.com/dougmoscrop/serverless-http/issues/34

**Comment by goodman98** [comment]
I am using the serverless too.  It was the same issue!

Thank you for helping me.

**Comment by tomyates** [comment]
I was using serverless too, thanks for the help!

**Comment by shanmugarajbe** [comment]
> Hi!
> My issue is I was using the _serverless_ framework with API gateway.
> There was some problems with the binary support which were fixed with a plugin and some configs, see this issue for more details: [dougmoscrop/serverless-http#34](https://github.com/dougmoscrop/serverless-http/issues/34)

Thanks for the help. I am using serverless and had the same issue.
